version: '3'
services:
    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - '/data/db'
    docker:
        image: docker:dind
        privileged: true
        restart: always
        tty: true
        volumes:
            - '/var/lib/docker'
    webide:
        image: node:latest
        privileged: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NODE_ENV: prod
        ports:
            - "3000" 
        depends_on:
            - mongo
            - docker
        volumes:
            - '.:/home/app'
            - '/home/app/node_modules'
                        
networks:
  default:
    driver: bridge
