version: '3'
services:
    mongo:
        image: mongo
        ports:
            - '27017:27017'
        environment:
            - "constraint:node==ip-10-0-57-22"
        volumes:
            - '/data/db'
    docker:
        image: docker:dind
        privileged: true
        volumes:
            - '/var/lib/docker'
    webide:
        image: node
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NODE_ENV: prod
        ports:
            - "3000"
        depends_on:
            - docker
            - mongo
        volumes:
            - '.:/home/app'
            - '/home/app/node_modules'
                        
networks:
  default:
    driver: bridge
